---
title: Hexa Global
author: Admin
email: admin@hexaglobal.io
description: Hexa Global brings honesty and fun to Sofware House while helping customers
  build website, system information,etc..
baseurl: "/ubuild-jekyll"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
